name: Отмена предыдущих тестов
on:
  push:
    branches:
      - master

jobs:
  Cancel:
    name: 'Отмена Ненужных Билдов'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa
        with:
          workflow_id: 9143745, 5560543
          access_token: ${{ github.token }}
